// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::bevy_transform_type::BevyTransform;
use super::vec_3_space_type::Vec3Space;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct Bot {
    pub id: u64,
    pub position: BevyTransform,
    pub alive: bool,
    pub movement_dir: Vec3Space,
    pub rotation_dir: f32,
}

impl __sdk::InModule for Bot {
    type Module = super::RemoteModule;
}
