// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::bevy_transform_type::BevyTransform;
use super::bot_type::Bot;
use super::vec_3_type::Vec3;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `bots`.
///
/// Obtain a handle from the [`BotsTableAccess::bots`] method on [`super::RemoteTables`],
/// like `ctx.db.bots()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.bots().on_insert(...)`.
pub struct BotsTableHandle<'ctx> {
    imp: __sdk::TableHandle<Bot>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `bots`.
///
/// Implemented for [`super::RemoteTables`].
pub trait BotsTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`BotsTableHandle`], which mediates access to the table `bots`.
    fn bots(&self) -> BotsTableHandle<'_>;
}

impl BotsTableAccess for super::RemoteTables {
    fn bots(&self) -> BotsTableHandle<'_> {
        BotsTableHandle {
            imp: self.imp.get_table::<Bot>("bots"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct BotsInsertCallbackId(__sdk::CallbackId);
pub struct BotsDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for BotsTableHandle<'ctx> {
    type Row = Bot;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = Bot> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = BotsInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> BotsInsertCallbackId {
        BotsInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: BotsInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = BotsDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> BotsDeleteCallbackId {
        BotsDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: BotsDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<Bot>("bots");
    _table.add_unique_constraint::<u64>("id", |row| &row.id);
}
pub struct BotsUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for BotsTableHandle<'ctx> {
    type UpdateCallbackId = BotsUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> BotsUpdateCallbackId {
        BotsUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: BotsUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::TableUpdate<__ws::BsatnFormat>,
) -> __sdk::Result<__sdk::TableUpdate<Bot>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<Bot>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

/// Access to the `id` unique index on the table `bots`,
/// which allows point queries on the field of the same name
/// via the [`BotsIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.bots().id().find(...)`.
pub struct BotsIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<Bot, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> BotsTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `bots`.
    pub fn id(&self) -> BotsIdUnique<'ctx> {
        BotsIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> BotsIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<Bot> {
        self.imp.find(col_val)
    }
}
