// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct DamageObstacleArgs {
    pub id: u64,
    pub damage: u32,
}

impl From<DamageObstacleArgs> for super::Reducer {
    fn from(args: DamageObstacleArgs) -> Self {
        Self::DamageObstacle {
            id: args.id,
            damage: args.damage,
        }
    }
}

impl __sdk::InModule for DamageObstacleArgs {
    type Module = super::RemoteModule;
}

pub struct DamageObstacleCallbackId(__sdk::CallbackId);

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `damage_obstacle`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait damage_obstacle {
    /// Request that the remote module invoke the reducer `damage_obstacle` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed by listening for [`Self::on_damage_obstacle`] callbacks.
    fn damage_obstacle(&self, id: u64, damage: u32) -> __sdk::Result<()>;
    /// Register a callback to run whenever we are notified of an invocation of the reducer `damage_obstacle`.
    ///
    /// Callbacks should inspect the [`__sdk::ReducerEvent`] contained in the [`super::ReducerEventContext`]
    /// to determine the reducer's status.
    ///
    /// The returned [`DamageObstacleCallbackId`] can be passed to [`Self::remove_on_damage_obstacle`]
    /// to cancel the callback.
    fn on_damage_obstacle(
        &self,
        callback: impl FnMut(&super::ReducerEventContext, &u64, &u32) + Send + 'static,
    ) -> DamageObstacleCallbackId;
    /// Cancel a callback previously registered by [`Self::on_damage_obstacle`],
    /// causing it not to run in the future.
    fn remove_on_damage_obstacle(&self, callback: DamageObstacleCallbackId);
}

impl damage_obstacle for super::RemoteReducers {
    fn damage_obstacle(&self, id: u64, damage: u32) -> __sdk::Result<()> {
        self.imp
            .call_reducer("damage_obstacle", DamageObstacleArgs { id, damage })
    }
    fn on_damage_obstacle(
        &self,
        mut callback: impl FnMut(&super::ReducerEventContext, &u64, &u32) + Send + 'static,
    ) -> DamageObstacleCallbackId {
        DamageObstacleCallbackId(self.imp.on_reducer(
            "damage_obstacle",
            Box::new(move |ctx: &super::ReducerEventContext| {
                let super::ReducerEventContext {
                    event:
                        __sdk::ReducerEvent {
                            reducer: super::Reducer::DamageObstacle { id, damage },
                            ..
                        },
                    ..
                } = ctx
                else {
                    unreachable!()
                };
                callback(ctx, id, damage)
            }),
        ))
    }
    fn remove_on_damage_obstacle(&self, callback: DamageObstacleCallbackId) {
        self.imp.remove_on_reducer("damage_obstacle", callback.0)
    }
}

#[allow(non_camel_case_types)]
#[doc(hidden)]
/// Extension trait for setting the call-flags for the reducer `damage_obstacle`.
///
/// Implemented for [`super::SetReducerFlags`].
///
/// This type is currently unstable and may be removed without a major version bump.
pub trait set_flags_for_damage_obstacle {
    /// Set the call-reducer flags for the reducer `damage_obstacle` to `flags`.
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    fn damage_obstacle(&self, flags: __ws::CallReducerFlags);
}

impl set_flags_for_damage_obstacle for super::SetReducerFlags {
    fn damage_obstacle(&self, flags: __ws::CallReducerFlags) {
        self.imp.set_call_reducer_flags("damage_obstacle", flags);
    }
}
