// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct DecreaseGridLoadArgs {
    pub identity: __sdk::Identity,
    pub load: i32,
}

impl From<DecreaseGridLoadArgs> for super::Reducer {
    fn from(args: DecreaseGridLoadArgs) -> Self {
        Self::DecreaseGridLoad {
            identity: args.identity,
            load: args.load,
        }
    }
}

impl __sdk::InModule for DecreaseGridLoadArgs {
    type Module = super::RemoteModule;
}

pub struct DecreaseGridLoadCallbackId(__sdk::CallbackId);

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `decrease_grid_load`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait decrease_grid_load {
    /// Request that the remote module invoke the reducer `decrease_grid_load` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed by listening for [`Self::on_decrease_grid_load`] callbacks.
    fn decrease_grid_load(&self, identity: __sdk::Identity, load: i32) -> __sdk::Result<()>;
    /// Register a callback to run whenever we are notified of an invocation of the reducer `decrease_grid_load`.
    ///
    /// Callbacks should inspect the [`__sdk::ReducerEvent`] contained in the [`super::ReducerEventContext`]
    /// to determine the reducer's status.
    ///
    /// The returned [`DecreaseGridLoadCallbackId`] can be passed to [`Self::remove_on_decrease_grid_load`]
    /// to cancel the callback.
    fn on_decrease_grid_load(
        &self,
        callback: impl FnMut(&super::ReducerEventContext, &__sdk::Identity, &i32) + Send + 'static,
    ) -> DecreaseGridLoadCallbackId;
    /// Cancel a callback previously registered by [`Self::on_decrease_grid_load`],
    /// causing it not to run in the future.
    fn remove_on_decrease_grid_load(&self, callback: DecreaseGridLoadCallbackId);
}

impl decrease_grid_load for super::RemoteReducers {
    fn decrease_grid_load(&self, identity: __sdk::Identity, load: i32) -> __sdk::Result<()> {
        self.imp.call_reducer(
            "decrease_grid_load",
            DecreaseGridLoadArgs { identity, load },
        )
    }
    fn on_decrease_grid_load(
        &self,
        mut callback: impl FnMut(&super::ReducerEventContext, &__sdk::Identity, &i32) + Send + 'static,
    ) -> DecreaseGridLoadCallbackId {
        DecreaseGridLoadCallbackId(self.imp.on_reducer(
            "decrease_grid_load",
            Box::new(move |ctx: &super::ReducerEventContext| {
                let super::ReducerEventContext {
                    event:
                        __sdk::ReducerEvent {
                            reducer: super::Reducer::DecreaseGridLoad { identity, load },
                            ..
                        },
                    ..
                } = ctx
                else {
                    unreachable!()
                };
                callback(ctx, identity, load)
            }),
        ))
    }
    fn remove_on_decrease_grid_load(&self, callback: DecreaseGridLoadCallbackId) {
        self.imp.remove_on_reducer("decrease_grid_load", callback.0)
    }
}

#[allow(non_camel_case_types)]
#[doc(hidden)]
/// Extension trait for setting the call-flags for the reducer `decrease_grid_load`.
///
/// Implemented for [`super::SetReducerFlags`].
///
/// This type is currently unstable and may be removed without a major version bump.
pub trait set_flags_for_decrease_grid_load {
    /// Set the call-reducer flags for the reducer `decrease_grid_load` to `flags`.
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    fn decrease_grid_load(&self, flags: __ws::CallReducerFlags);
}

impl set_flags_for_decrease_grid_load for super::SetReducerFlags {
    fn decrease_grid_load(&self, flags: __ws::CallReducerFlags) {
        self.imp.set_call_reducer_flags("decrease_grid_load", flags);
    }
}
