// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::leaderboard_type::Leaderboard;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `leaderboard`.
///
/// Obtain a handle from the [`LeaderboardTableAccess::leaderboard`] method on [`super::RemoteTables`],
/// like `ctx.db.leaderboard()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.leaderboard().on_insert(...)`.
pub struct LeaderboardTableHandle<'ctx> {
    imp: __sdk::TableHandle<Leaderboard>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `leaderboard`.
///
/// Implemented for [`super::RemoteTables`].
pub trait LeaderboardTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`LeaderboardTableHandle`], which mediates access to the table `leaderboard`.
    fn leaderboard(&self) -> LeaderboardTableHandle<'_>;
}

impl LeaderboardTableAccess for super::RemoteTables {
    fn leaderboard(&self) -> LeaderboardTableHandle<'_> {
        LeaderboardTableHandle {
            imp: self.imp.get_table::<Leaderboard>("leaderboard"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct LeaderboardInsertCallbackId(__sdk::CallbackId);
pub struct LeaderboardDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for LeaderboardTableHandle<'ctx> {
    type Row = Leaderboard;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = Leaderboard> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = LeaderboardInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> LeaderboardInsertCallbackId {
        LeaderboardInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: LeaderboardInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = LeaderboardDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> LeaderboardDeleteCallbackId {
        LeaderboardDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: LeaderboardDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<Leaderboard>("leaderboard");
    _table.add_unique_constraint::<u64>("id", |row| &row.id);
}
pub struct LeaderboardUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for LeaderboardTableHandle<'ctx> {
    type UpdateCallbackId = LeaderboardUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> LeaderboardUpdateCallbackId {
        LeaderboardUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: LeaderboardUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::TableUpdate<__ws::BsatnFormat>,
) -> __sdk::Result<__sdk::TableUpdate<Leaderboard>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<Leaderboard>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

/// Access to the `id` unique index on the table `leaderboard`,
/// which allows point queries on the field of the same name
/// via the [`LeaderboardIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.leaderboard().id().find(...)`.
pub struct LeaderboardIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<Leaderboard, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> LeaderboardTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `leaderboard`.
    pub fn id(&self) -> LeaderboardIdUnique<'ctx> {
        LeaderboardIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> LeaderboardIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<Leaderboard> {
        self.imp.find(col_val)
    }
}
