// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::obstacle_type::Obstacle;
use super::vec_2_type::Vec2;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `obstacle`.
///
/// Obtain a handle from the [`ObstacleTableAccess::obstacle`] method on [`super::RemoteTables`],
/// like `ctx.db.obstacle()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.obstacle().on_insert(...)`.
pub struct ObstacleTableHandle<'ctx> {
    imp: __sdk::TableHandle<Obstacle>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `obstacle`.
///
/// Implemented for [`super::RemoteTables`].
pub trait ObstacleTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`ObstacleTableHandle`], which mediates access to the table `obstacle`.
    fn obstacle(&self) -> ObstacleTableHandle<'_>;
}

impl ObstacleTableAccess for super::RemoteTables {
    fn obstacle(&self) -> ObstacleTableHandle<'_> {
        ObstacleTableHandle {
            imp: self.imp.get_table::<Obstacle>("obstacle"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct ObstacleInsertCallbackId(__sdk::CallbackId);
pub struct ObstacleDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for ObstacleTableHandle<'ctx> {
    type Row = Obstacle;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = Obstacle> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = ObstacleInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> ObstacleInsertCallbackId {
        ObstacleInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: ObstacleInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = ObstacleDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> ObstacleDeleteCallbackId {
        ObstacleDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: ObstacleDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<Obstacle>("obstacle");
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::TableUpdate<__ws::BsatnFormat>,
) -> __sdk::Result<__sdk::TableUpdate<Obstacle>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<Obstacle>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}
