// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct PlayerConnectedArgs {}

impl From<PlayerConnectedArgs> for super::Reducer {
    fn from(args: PlayerConnectedArgs) -> Self {
        Self::PlayerConnected
    }
}

impl __sdk::InModule for PlayerConnectedArgs {
    type Module = super::RemoteModule;
}

pub struct PlayerConnectedCallbackId(__sdk::CallbackId);

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `player_connected`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait player_connected {
    /// Request that the remote module invoke the reducer `player_connected` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed by listening for [`Self::on_player_connected`] callbacks.
    fn player_connected(&self) -> __sdk::Result<()>;
    /// Register a callback to run whenever we are notified of an invocation of the reducer `player_connected`.
    ///
    /// Callbacks should inspect the [`__sdk::ReducerEvent`] contained in the [`super::ReducerEventContext`]
    /// to determine the reducer's status.
    ///
    /// The returned [`PlayerConnectedCallbackId`] can be passed to [`Self::remove_on_player_connected`]
    /// to cancel the callback.
    fn on_player_connected(
        &self,
        callback: impl FnMut(&super::ReducerEventContext) + Send + 'static,
    ) -> PlayerConnectedCallbackId;
    /// Cancel a callback previously registered by [`Self::on_player_connected`],
    /// causing it not to run in the future.
    fn remove_on_player_connected(&self, callback: PlayerConnectedCallbackId);
}

impl player_connected for super::RemoteReducers {
    fn player_connected(&self) -> __sdk::Result<()> {
        self.imp
            .call_reducer("player_connected", PlayerConnectedArgs {})
    }
    fn on_player_connected(
        &self,
        mut callback: impl FnMut(&super::ReducerEventContext) + Send + 'static,
    ) -> PlayerConnectedCallbackId {
        PlayerConnectedCallbackId(self.imp.on_reducer(
            "player_connected",
            Box::new(move |ctx: &super::ReducerEventContext| {
                let super::ReducerEventContext {
                    event:
                        __sdk::ReducerEvent {
                            reducer: super::Reducer::PlayerConnected {},
                            ..
                        },
                    ..
                } = ctx
                else {
                    unreachable!()
                };
                callback(ctx)
            }),
        ))
    }
    fn remove_on_player_connected(&self, callback: PlayerConnectedCallbackId) {
        self.imp.remove_on_reducer("player_connected", callback.0)
    }
}

#[allow(non_camel_case_types)]
#[doc(hidden)]
/// Extension trait for setting the call-flags for the reducer `player_connected`.
///
/// Implemented for [`super::SetReducerFlags`].
///
/// This type is currently unstable and may be removed without a major version bump.
pub trait set_flags_for_player_connected {
    /// Set the call-reducer flags for the reducer `player_connected` to `flags`.
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    fn player_connected(&self, flags: __ws::CallReducerFlags);
}

impl set_flags_for_player_connected for super::SetReducerFlags {
    fn player_connected(&self, flags: __ws::CallReducerFlags) {
        self.imp.set_call_reducer_flags("player_connected", flags);
    }
}
