// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct SetHookExtendingArgs {
    pub is_extending: bool,
}

impl From<SetHookExtendingArgs> for super::Reducer {
    fn from(args: SetHookExtendingArgs) -> Self {
        Self::SetHookExtending {
            is_extending: args.is_extending,
        }
    }
}

impl __sdk::InModule for SetHookExtendingArgs {
    type Module = super::RemoteModule;
}

pub struct SetHookExtendingCallbackId(__sdk::CallbackId);

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `set_hook_extending`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait set_hook_extending {
    /// Request that the remote module invoke the reducer `set_hook_extending` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed by listening for [`Self::on_set_hook_extending`] callbacks.
    fn set_hook_extending(&self, is_extending: bool) -> __sdk::Result<()>;
    /// Register a callback to run whenever we are notified of an invocation of the reducer `set_hook_extending`.
    ///
    /// Callbacks should inspect the [`__sdk::ReducerEvent`] contained in the [`super::ReducerEventContext`]
    /// to determine the reducer's status.
    ///
    /// The returned [`SetHookExtendingCallbackId`] can be passed to [`Self::remove_on_set_hook_extending`]
    /// to cancel the callback.
    fn on_set_hook_extending(
        &self,
        callback: impl FnMut(&super::ReducerEventContext, &bool) + Send + 'static,
    ) -> SetHookExtendingCallbackId;
    /// Cancel a callback previously registered by [`Self::on_set_hook_extending`],
    /// causing it not to run in the future.
    fn remove_on_set_hook_extending(&self, callback: SetHookExtendingCallbackId);
}

impl set_hook_extending for super::RemoteReducers {
    fn set_hook_extending(&self, is_extending: bool) -> __sdk::Result<()> {
        self.imp
            .call_reducer("set_hook_extending", SetHookExtendingArgs { is_extending })
    }
    fn on_set_hook_extending(
        &self,
        mut callback: impl FnMut(&super::ReducerEventContext, &bool) + Send + 'static,
    ) -> SetHookExtendingCallbackId {
        SetHookExtendingCallbackId(self.imp.on_reducer(
            "set_hook_extending",
            Box::new(move |ctx: &super::ReducerEventContext| {
                let super::ReducerEventContext {
                    event:
                        __sdk::ReducerEvent {
                            reducer: super::Reducer::SetHookExtending { is_extending },
                            ..
                        },
                    ..
                } = ctx
                else {
                    unreachable!()
                };
                callback(ctx, is_extending)
            }),
        ))
    }
    fn remove_on_set_hook_extending(&self, callback: SetHookExtendingCallbackId) {
        self.imp.remove_on_reducer("set_hook_extending", callback.0)
    }
}

#[allow(non_camel_case_types)]
#[doc(hidden)]
/// Extension trait for setting the call-flags for the reducer `set_hook_extending`.
///
/// Implemented for [`super::SetReducerFlags`].
///
/// This type is currently unstable and may be removed without a major version bump.
pub trait set_flags_for_set_hook_extending {
    /// Set the call-reducer flags for the reducer `set_hook_extending` to `flags`.
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    fn set_hook_extending(&self, flags: __ws::CallReducerFlags);
}

impl set_flags_for_set_hook_extending for super::SetReducerFlags {
    fn set_hook_extending(&self, flags: __ws::CallReducerFlags) {
        self.imp.set_call_reducer_flags("set_hook_extending", flags);
    }
}
