// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::bevy_transform_type::BevyTransform;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct Track {
    pub owner_identity: __sdk::Identity,
    pub position: BevyTransform,
    pub rotation: f32,
    pub width: f32,
    pub height: f32,
    pub id: u64,
}

impl __sdk::InModule for Track {
    type Module = super::RemoteModule;
}
