// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::bevy_transform_type::BevyTransform;
use super::track_type::Track;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `track`.
///
/// Obtain a handle from the [`TrackTableAccess::track`] method on [`super::RemoteTables`],
/// like `ctx.db.track()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.track().on_insert(...)`.
pub struct TrackTableHandle<'ctx> {
    imp: __sdk::TableHandle<Track>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `track`.
///
/// Implemented for [`super::RemoteTables`].
pub trait TrackTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`TrackTableHandle`], which mediates access to the table `track`.
    fn track(&self) -> TrackTableHandle<'_>;
}

impl TrackTableAccess for super::RemoteTables {
    fn track(&self) -> TrackTableHandle<'_> {
        TrackTableHandle {
            imp: self.imp.get_table::<Track>("track"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct TrackInsertCallbackId(__sdk::CallbackId);
pub struct TrackDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for TrackTableHandle<'ctx> {
    type Row = Track;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = Track> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = TrackInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> TrackInsertCallbackId {
        TrackInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: TrackInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = TrackDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> TrackDeleteCallbackId {
        TrackDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: TrackDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<Track>("track");
    _table.add_unique_constraint::<__sdk::Identity>("owner_identity", |row| &row.owner_identity);
}
pub struct TrackUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for TrackTableHandle<'ctx> {
    type UpdateCallbackId = TrackUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> TrackUpdateCallbackId {
        TrackUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: TrackUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::TableUpdate<__ws::BsatnFormat>,
) -> __sdk::Result<__sdk::TableUpdate<Track>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<Track>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

/// Access to the `owner_identity` unique index on the table `track`,
/// which allows point queries on the field of the same name
/// via the [`TrackOwnerIdentityUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.track().owner_identity().find(...)`.
pub struct TrackOwnerIdentityUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<Track, __sdk::Identity>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> TrackTableHandle<'ctx> {
    /// Get a handle on the `owner_identity` unique index on the table `track`.
    pub fn owner_identity(&self) -> TrackOwnerIdentityUnique<'ctx> {
        TrackOwnerIdentityUnique {
            imp: self
                .imp
                .get_unique_constraint::<__sdk::Identity>("owner_identity"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> TrackOwnerIdentityUnique<'ctx> {
    /// Find the subscribed row whose `owner_identity` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &__sdk::Identity) -> Option<Track> {
        self.imp.find(col_val)
    }
}
