// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct UpdateOwnerGridArgs {
    pub load: i32,
    pub next_free_x: i32,
    pub next_free_y: i32,
}

impl From<UpdateOwnerGridArgs> for super::Reducer {
    fn from(args: UpdateOwnerGridArgs) -> Self {
        Self::UpdateOwnerGrid {
            load: args.load,
            next_free_x: args.next_free_x,
            next_free_y: args.next_free_y,
        }
    }
}

impl __sdk::InModule for UpdateOwnerGridArgs {
    type Module = super::RemoteModule;
}

pub struct UpdateOwnerGridCallbackId(__sdk::CallbackId);

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `update_owner_grid`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait update_owner_grid {
    /// Request that the remote module invoke the reducer `update_owner_grid` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed by listening for [`Self::on_update_owner_grid`] callbacks.
    fn update_owner_grid(&self, load: i32, next_free_x: i32, next_free_y: i32)
        -> __sdk::Result<()>;
    /// Register a callback to run whenever we are notified of an invocation of the reducer `update_owner_grid`.
    ///
    /// Callbacks should inspect the [`__sdk::ReducerEvent`] contained in the [`super::ReducerEventContext`]
    /// to determine the reducer's status.
    ///
    /// The returned [`UpdateOwnerGridCallbackId`] can be passed to [`Self::remove_on_update_owner_grid`]
    /// to cancel the callback.
    fn on_update_owner_grid(
        &self,
        callback: impl FnMut(&super::ReducerEventContext, &i32, &i32, &i32) + Send + 'static,
    ) -> UpdateOwnerGridCallbackId;
    /// Cancel a callback previously registered by [`Self::on_update_owner_grid`],
    /// causing it not to run in the future.
    fn remove_on_update_owner_grid(&self, callback: UpdateOwnerGridCallbackId);
}

impl update_owner_grid for super::RemoteReducers {
    fn update_owner_grid(
        &self,
        load: i32,
        next_free_x: i32,
        next_free_y: i32,
    ) -> __sdk::Result<()> {
        self.imp.call_reducer(
            "update_owner_grid",
            UpdateOwnerGridArgs {
                load,
                next_free_x,
                next_free_y,
            },
        )
    }
    fn on_update_owner_grid(
        &self,
        mut callback: impl FnMut(&super::ReducerEventContext, &i32, &i32, &i32) + Send + 'static,
    ) -> UpdateOwnerGridCallbackId {
        UpdateOwnerGridCallbackId(self.imp.on_reducer(
            "update_owner_grid",
            Box::new(move |ctx: &super::ReducerEventContext| {
                let super::ReducerEventContext {
                    event:
                        __sdk::ReducerEvent {
                            reducer:
                                super::Reducer::UpdateOwnerGrid {
                                    load,
                                    next_free_x,
                                    next_free_y,
                                },
                            ..
                        },
                    ..
                } = ctx
                else {
                    unreachable!()
                };
                callback(ctx, load, next_free_x, next_free_y)
            }),
        ))
    }
    fn remove_on_update_owner_grid(&self, callback: UpdateOwnerGridCallbackId) {
        self.imp.remove_on_reducer("update_owner_grid", callback.0)
    }
}

#[allow(non_camel_case_types)]
#[doc(hidden)]
/// Extension trait for setting the call-flags for the reducer `update_owner_grid`.
///
/// Implemented for [`super::SetReducerFlags`].
///
/// This type is currently unstable and may be removed without a major version bump.
pub trait set_flags_for_update_owner_grid {
    /// Set the call-reducer flags for the reducer `update_owner_grid` to `flags`.
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    fn update_owner_grid(&self, flags: __ws::CallReducerFlags);
}

impl set_flags_for_update_owner_grid for super::SetReducerFlags {
    fn update_owner_grid(&self, flags: __ws::CallReducerFlags) {
        self.imp.set_call_reducer_flags("update_owner_grid", flags);
    }
}
