// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct UpdateHooksArgs {
    pub delta_time: f32,
}

impl From<UpdateHooksArgs> for super::Reducer {
    fn from(args: UpdateHooksArgs) -> Self {
        Self::UpdateHooks {
            delta_time: args.delta_time,
        }
    }
}

impl __sdk::InModule for UpdateHooksArgs {
    type Module = super::RemoteModule;
}

pub struct UpdateHooksCallbackId(__sdk::CallbackId);

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `update_hooks`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait update_hooks {
    /// Request that the remote module invoke the reducer `update_hooks` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed by listening for [`Self::on_update_hooks`] callbacks.
    fn update_hooks(&self, delta_time: f32) -> __sdk::Result<()>;
    /// Register a callback to run whenever we are notified of an invocation of the reducer `update_hooks`.
    ///
    /// Callbacks should inspect the [`__sdk::ReducerEvent`] contained in the [`super::ReducerEventContext`]
    /// to determine the reducer's status.
    ///
    /// The returned [`UpdateHooksCallbackId`] can be passed to [`Self::remove_on_update_hooks`]
    /// to cancel the callback.
    fn on_update_hooks(
        &self,
        callback: impl FnMut(&super::ReducerEventContext, &f32) + Send + 'static,
    ) -> UpdateHooksCallbackId;
    /// Cancel a callback previously registered by [`Self::on_update_hooks`],
    /// causing it not to run in the future.
    fn remove_on_update_hooks(&self, callback: UpdateHooksCallbackId);
}

impl update_hooks for super::RemoteReducers {
    fn update_hooks(&self, delta_time: f32) -> __sdk::Result<()> {
        self.imp
            .call_reducer("update_hooks", UpdateHooksArgs { delta_time })
    }
    fn on_update_hooks(
        &self,
        mut callback: impl FnMut(&super::ReducerEventContext, &f32) + Send + 'static,
    ) -> UpdateHooksCallbackId {
        UpdateHooksCallbackId(self.imp.on_reducer(
            "update_hooks",
            Box::new(move |ctx: &super::ReducerEventContext| {
                let super::ReducerEventContext {
                    event:
                        __sdk::ReducerEvent {
                            reducer: super::Reducer::UpdateHooks { delta_time },
                            ..
                        },
                    ..
                } = ctx
                else {
                    unreachable!()
                };
                callback(ctx, delta_time)
            }),
        ))
    }
    fn remove_on_update_hooks(&self, callback: UpdateHooksCallbackId) {
        self.imp.remove_on_reducer("update_hooks", callback.0)
    }
}

#[allow(non_camel_case_types)]
#[doc(hidden)]
/// Extension trait for setting the call-flags for the reducer `update_hooks`.
///
/// Implemented for [`super::SetReducerFlags`].
///
/// This type is currently unstable and may be removed without a major version bump.
pub trait set_flags_for_update_hooks {
    /// Set the call-reducer flags for the reducer `update_hooks` to `flags`.
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    fn update_hooks(&self, flags: __ws::CallReducerFlags);
}

impl set_flags_for_update_hooks for super::SetReducerFlags {
    fn update_hooks(&self, flags: __ws::CallReducerFlags) {
        self.imp.set_call_reducer_flags("update_hooks", flags);
    }
}
