// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct UpdateLeaderboardArgs {
    pub player_identity: __sdk::Identity,
    pub id_leaderboard: u64,
}

impl From<UpdateLeaderboardArgs> for super::Reducer {
    fn from(args: UpdateLeaderboardArgs) -> Self {
        Self::UpdateLeaderboard {
            player_identity: args.player_identity,
            id_leaderboard: args.id_leaderboard,
        }
    }
}

impl __sdk::InModule for UpdateLeaderboardArgs {
    type Module = super::RemoteModule;
}

pub struct UpdateLeaderboardCallbackId(__sdk::CallbackId);

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `update_leaderboard`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait update_leaderboard {
    /// Request that the remote module invoke the reducer `update_leaderboard` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed by listening for [`Self::on_update_leaderboard`] callbacks.
    fn update_leaderboard(
        &self,
        player_identity: __sdk::Identity,
        id_leaderboard: u64,
    ) -> __sdk::Result<()>;
    /// Register a callback to run whenever we are notified of an invocation of the reducer `update_leaderboard`.
    ///
    /// Callbacks should inspect the [`__sdk::ReducerEvent`] contained in the [`super::ReducerEventContext`]
    /// to determine the reducer's status.
    ///
    /// The returned [`UpdateLeaderboardCallbackId`] can be passed to [`Self::remove_on_update_leaderboard`]
    /// to cancel the callback.
    fn on_update_leaderboard(
        &self,
        callback: impl FnMut(&super::ReducerEventContext, &__sdk::Identity, &u64) + Send + 'static,
    ) -> UpdateLeaderboardCallbackId;
    /// Cancel a callback previously registered by [`Self::on_update_leaderboard`],
    /// causing it not to run in the future.
    fn remove_on_update_leaderboard(&self, callback: UpdateLeaderboardCallbackId);
}

impl update_leaderboard for super::RemoteReducers {
    fn update_leaderboard(
        &self,
        player_identity: __sdk::Identity,
        id_leaderboard: u64,
    ) -> __sdk::Result<()> {
        self.imp.call_reducer(
            "update_leaderboard",
            UpdateLeaderboardArgs {
                player_identity,
                id_leaderboard,
            },
        )
    }
    fn on_update_leaderboard(
        &self,
        mut callback: impl FnMut(&super::ReducerEventContext, &__sdk::Identity, &u64) + Send + 'static,
    ) -> UpdateLeaderboardCallbackId {
        UpdateLeaderboardCallbackId(self.imp.on_reducer(
            "update_leaderboard",
            Box::new(move |ctx: &super::ReducerEventContext| {
                let super::ReducerEventContext {
                    event:
                        __sdk::ReducerEvent {
                            reducer:
                                super::Reducer::UpdateLeaderboard {
                                    player_identity,
                                    id_leaderboard,
                                },
                            ..
                        },
                    ..
                } = ctx
                else {
                    unreachable!()
                };
                callback(ctx, player_identity, id_leaderboard)
            }),
        ))
    }
    fn remove_on_update_leaderboard(&self, callback: UpdateLeaderboardCallbackId) {
        self.imp.remove_on_reducer("update_leaderboard", callback.0)
    }
}

#[allow(non_camel_case_types)]
#[doc(hidden)]
/// Extension trait for setting the call-flags for the reducer `update_leaderboard`.
///
/// Implemented for [`super::SetReducerFlags`].
///
/// This type is currently unstable and may be removed without a major version bump.
pub trait set_flags_for_update_leaderboard {
    /// Set the call-reducer flags for the reducer `update_leaderboard` to `flags`.
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    fn update_leaderboard(&self, flags: __ws::CallReducerFlags);
}

impl set_flags_for_update_leaderboard for super::SetReducerFlags {
    fn update_leaderboard(&self, flags: __ws::CallReducerFlags) {
        self.imp.set_call_reducer_flags("update_leaderboard", flags);
    }
}
