// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::vec_2_type::Vec2;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct UpdateHookPositionArgs {
    pub identity: __sdk::Identity,
    pub position: Vec2,
    pub rotation: f32,
}

impl From<UpdateHookPositionArgs> for super::Reducer {
    fn from(args: UpdateHookPositionArgs) -> Self {
        Self::UpdateHookPosition {
            identity: args.identity,
            position: args.position,
            rotation: args.rotation,
        }
    }
}

impl __sdk::InModule for UpdateHookPositionArgs {
    type Module = super::RemoteModule;
}

pub struct UpdateHookPositionCallbackId(__sdk::CallbackId);

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `update_hook_position`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait update_hook_position {
    /// Request that the remote module invoke the reducer `update_hook_position` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed by listening for [`Self::on_update_hook_position`] callbacks.
    fn update_hook_position(
        &self,
        identity: __sdk::Identity,
        position: Vec2,
        rotation: f32,
    ) -> __sdk::Result<()>;
    /// Register a callback to run whenever we are notified of an invocation of the reducer `update_hook_position`.
    ///
    /// Callbacks should inspect the [`__sdk::ReducerEvent`] contained in the [`super::ReducerEventContext`]
    /// to determine the reducer's status.
    ///
    /// The returned [`UpdateHookPositionCallbackId`] can be passed to [`Self::remove_on_update_hook_position`]
    /// to cancel the callback.
    fn on_update_hook_position(
        &self,
        callback: impl FnMut(&super::ReducerEventContext, &__sdk::Identity, &Vec2, &f32)
            + Send
            + 'static,
    ) -> UpdateHookPositionCallbackId;
    /// Cancel a callback previously registered by [`Self::on_update_hook_position`],
    /// causing it not to run in the future.
    fn remove_on_update_hook_position(&self, callback: UpdateHookPositionCallbackId);
}

impl update_hook_position for super::RemoteReducers {
    fn update_hook_position(
        &self,
        identity: __sdk::Identity,
        position: Vec2,
        rotation: f32,
    ) -> __sdk::Result<()> {
        self.imp.call_reducer(
            "update_hook_position",
            UpdateHookPositionArgs {
                identity,
                position,
                rotation,
            },
        )
    }
    fn on_update_hook_position(
        &self,
        mut callback: impl FnMut(&super::ReducerEventContext, &__sdk::Identity, &Vec2, &f32)
            + Send
            + 'static,
    ) -> UpdateHookPositionCallbackId {
        UpdateHookPositionCallbackId(self.imp.on_reducer(
            "update_hook_position",
            Box::new(move |ctx: &super::ReducerEventContext| {
                let super::ReducerEventContext {
                    event:
                        __sdk::ReducerEvent {
                            reducer:
                                super::Reducer::UpdateHookPosition {
                                    identity,
                                    position,
                                    rotation,
                                },
                            ..
                        },
                    ..
                } = ctx
                else {
                    unreachable!()
                };
                callback(ctx, identity, position, rotation)
            }),
        ))
    }
    fn remove_on_update_hook_position(&self, callback: UpdateHookPositionCallbackId) {
        self.imp
            .remove_on_reducer("update_hook_position", callback.0)
    }
}

#[allow(non_camel_case_types)]
#[doc(hidden)]
/// Extension trait for setting the call-flags for the reducer `update_hook_position`.
///
/// Implemented for [`super::SetReducerFlags`].
///
/// This type is currently unstable and may be removed without a major version bump.
pub trait set_flags_for_update_hook_position {
    /// Set the call-reducer flags for the reducer `update_hook_position` to `flags`.
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    fn update_hook_position(&self, flags: __ws::CallReducerFlags);
}

impl set_flags_for_update_hook_position for super::SetReducerFlags {
    fn update_hook_position(&self, flags: __ws::CallReducerFlags) {
        self.imp
            .set_call_reducer_flags("update_hook_position", flags);
    }
}
