// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::bevy_transform_type::BevyTransform;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct UpdatePlayerPositionArgs {
    pub bevy_transform: BevyTransform,
}

impl From<UpdatePlayerPositionArgs> for super::Reducer {
    fn from(args: UpdatePlayerPositionArgs) -> Self {
        Self::UpdatePlayerPosition {
            bevy_transform: args.bevy_transform,
        }
    }
}

impl __sdk::InModule for UpdatePlayerPositionArgs {
    type Module = super::RemoteModule;
}

pub struct UpdatePlayerPositionCallbackId(__sdk::CallbackId);

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `update_player_position`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait update_player_position {
    /// Request that the remote module invoke the reducer `update_player_position` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed by listening for [`Self::on_update_player_position`] callbacks.
    fn update_player_position(&self, bevy_transform: BevyTransform) -> __sdk::Result<()>;
    /// Register a callback to run whenever we are notified of an invocation of the reducer `update_player_position`.
    ///
    /// Callbacks should inspect the [`__sdk::ReducerEvent`] contained in the [`super::ReducerEventContext`]
    /// to determine the reducer's status.
    ///
    /// The returned [`UpdatePlayerPositionCallbackId`] can be passed to [`Self::remove_on_update_player_position`]
    /// to cancel the callback.
    fn on_update_player_position(
        &self,
        callback: impl FnMut(&super::ReducerEventContext, &BevyTransform) + Send + 'static,
    ) -> UpdatePlayerPositionCallbackId;
    /// Cancel a callback previously registered by [`Self::on_update_player_position`],
    /// causing it not to run in the future.
    fn remove_on_update_player_position(&self, callback: UpdatePlayerPositionCallbackId);
}

impl update_player_position for super::RemoteReducers {
    fn update_player_position(&self, bevy_transform: BevyTransform) -> __sdk::Result<()> {
        self.imp.call_reducer(
            "update_player_position",
            UpdatePlayerPositionArgs { bevy_transform },
        )
    }
    fn on_update_player_position(
        &self,
        mut callback: impl FnMut(&super::ReducerEventContext, &BevyTransform) + Send + 'static,
    ) -> UpdatePlayerPositionCallbackId {
        UpdatePlayerPositionCallbackId(self.imp.on_reducer(
            "update_player_position",
            Box::new(move |ctx: &super::ReducerEventContext| {
                let super::ReducerEventContext {
                    event:
                        __sdk::ReducerEvent {
                            reducer: super::Reducer::UpdatePlayerPosition { bevy_transform },
                            ..
                        },
                    ..
                } = ctx
                else {
                    unreachable!()
                };
                callback(ctx, bevy_transform)
            }),
        ))
    }
    fn remove_on_update_player_position(&self, callback: UpdatePlayerPositionCallbackId) {
        self.imp
            .remove_on_reducer("update_player_position", callback.0)
    }
}

#[allow(non_camel_case_types)]
#[doc(hidden)]
/// Extension trait for setting the call-flags for the reducer `update_player_position`.
///
/// Implemented for [`super::SetReducerFlags`].
///
/// This type is currently unstable and may be removed without a major version bump.
pub trait set_flags_for_update_player_position {
    /// Set the call-reducer flags for the reducer `update_player_position` to `flags`.
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    fn update_player_position(&self, flags: __ws::CallReducerFlags);
}

impl set_flags_for_update_player_position for super::SetReducerFlags {
    fn update_player_position(&self, flags: __ws::CallReducerFlags) {
        self.imp
            .set_call_reducer_flags("update_player_position", flags);
    }
}
